# Complementing a Strand of DNA

dna = "CACATTGAGTGATTCCGGTCACAATTCGGCTTTTTATCAATATGCCGTCGGGCACCCGTTCGGTAGTGGGCGGATGGACACCTAACAATAGCGAGATGGCCCCGTTCTAGCTATGCACCCCATGATTTCCACATAAACTATTGATTGAGCAGGACTCAATGTTAGGAATTAAGTGATATTGGCGATCGTGGACGTAGTCGCGTGAGACTCTGACCGCCTAACCATGTACTGACGTAACCAACGAGGATGACTAATTGGAACCTCGGGGAGGTCAGCGGGTCGGTGTGGTACAAAACCAACACCTCTCAGCGTAACACCGGAACGTCCTGCGTTTTCCGGCTAGTGTACAAGCTTCGCTTGCCCCTGTGGTTCGTCGTAGCCGGCCGATCACTTCAACTGTACCCTGGCAAGGCACAAAGTACATAGTCATAGACTTTGTGAACGCCCTTCATGTACTCTTTACATCGAACATGAGGGGATAAACGACCAAGGTACGCGGGCAAGCTCCTCACAGATTTACATCGGGCTTCCTGCAGTATATTCTCTACGGAAACGGGGTGCCCCTCTTGGCAACGATCATCGCCGGCGGGAAGCCTGTGCGGTTTAATCCCTGGGACTGTACGCCGATATTATTAAAACTAGTTTACGGAGGTCTATCACGGAGAGGGCTGCGCTCCGTTTATGTCTCATCACACTGTTATGATCTTCTTGCTGCCCGTTATGCAGGGCCAAAGGGCGTTCTAAGCAGCGGTGTGTCGTTTGTAACTGATTTGTATATACTGTTTGTGGAGGTAAACGGCTATACGGTAGGGATCATTCACA"
dna = dna.replace("A", "t")
dna = dna.replace("T", "a")
dna = dna.replace("G", "c")
dna = dna.replace("C", "g")
dna = dna.replace("c", "C")
dna = dna.replace("g", "G")
dna = dna.replace("a", "A")
dna = dna.replace("t", "T")
dna = dna[::-1]
print(dna)
